const S=JSON.parse(localStorage.getItem("tf_state")||"null")||{level:1,coins:250,stars:{},theme:"emoji",sound:true,music:false,ach:[],version:2};
const $=id=>document.getElementById(id);
let game=null;
const UI={
show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.nav===id));window.scrollTo(0,0);},
save(){localStorage.setItem("tf_state",JSON.stringify(S));$("coins").textContent=S.coins;},
sound(type){if(!S.sound)return;try{const a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();const f={tap:420,match:620,triple:900,hint:520,shuffle:300}[type]||440;o.frequency.value=f;o.type="sine";g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.12);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.13)}catch(e){}},
toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(this.tt);this.tt=setTimeout(()=>t.classList.remove("show"),1400);},
start(level=S.level,theme=S.theme){game=new TFEngine($("board"),()=>this.gameUI());game.ui=this;this.show("gameScreen");game.start(level,theme);$("gameLevel").textContent=level;$("themeName").textContent=TF_CONTENT.themes[theme].name;},
gameUI(){if(!game)return;$("score").textContent=game.score.toLocaleString();$("combo").textContent=game.maxCombo;$("timer").textContent=Math.floor(game.elapsed);$("remaining").textContent=game.tiles.filter(t=>t.alive).length;$("trayCount").textContent=`${game.tray.length} / 7`;$("boardProgress").style.width=`${Math.max(0,100*(1-game.tiles.filter(t=>t.alive).length/game.tiles.length))}%`;const tray=$("tray");tray.innerHTML="";game.tray.forEach(x=>{const d=document.createElement("div");d.className="tray-tile";d.textContent=x.symbol;tray.appendChild(d)});document.querySelectorAll(".tool").forEach(b=>{const k=b.dataset.tool;b.querySelector("small").textContent=k==="undo"?game.tool.undo:k==="shuffle"?game.tool.shuffle:k==="wild"?game.tool.wild:"∞"});},
finish(win,data){if(!win){this.show("resultScreen");$("resultIcon").textContent="💥";$("resultKicker").textContent="TRAY FULL";$("resultTitle").textContent="Almost there";$("resultText").textContent="Use your tools to create more space.";$("resultStars").textContent="☆☆☆";$("nextBtn").textContent="Try Again";$("nextBtn").onclick=()=>this.start(game.level,S.theme);return}
let stars=data.score>=1800?3:data.score>=900?2:1;S.stars[game.level]=Math.max(S.stars[game.level]||0,stars);S.coins+=50+stars*25;if(game.level>=S.level)S.level=Math.min(TF_CONTENT.levelCount,game.level+1);this.unlock(data,stars);this.save();this.show("resultScreen");$("resultIcon").textContent=stars===3?"👑":"🏆";$("resultKicker").textContent="LEVEL COMPLETE";$("resultTitle").textContent=stars===3?"Flawless!":stars===2?"Great work!":"Nice clear!";$("resultText").textContent="The board is clear. Keep your streak going.";$("resultStars").textContent="★".repeat(stars)+"☆".repeat(3-stars);$("resultScore").textContent=data.score.toLocaleString();$("resultCombo").textContent=data.maxCombo;$("resultTime").textContent=data.time+"s";$("resultCoins").textContent=50+stars*25;$("nextBtn").textContent=game.level<TF_CONTENT.levelCount?"Next Level →":"Replay Level";$("nextBtn").onclick=()=>this.start(Math.min(TF_CONTENT.levelCount,game.level+1),S.theme);},
unlock(data,stars){const add=id=>{if(!S.ach.includes(id)){S.ach.push(id);this.toast("Achievement unlocked!");}};if(game.level===1)add("first");if(data.maxCombo>=5)add("combo5");if(data.toolUsed===0&&stars===3)add("perfect");if(game.level>=10)add("ten");if(game.level>=25)add("twentyfive");if(game.level>=50)add("fifty");$("achievementMini").textContent=S.ach.length+" unlocked";},
renderHome(){this.save();$("playLevel").textContent=S.level;$("achievementMini").textContent=S.ach.length+" unlocked";const wrap=$("themeCards");wrap.innerHTML="";["emoji","football","awards"].forEach(id=>{const t=TF_CONTENT.themes[id],b=document.createElement("button");b.className="theme-card";b.innerHTML=`<span>${t.icon}</span><b>${t.name}</b><small>${t.desc}</small>`;b.onclick=()=>{S.theme=id;this.save();this.start(S.level,id)};wrap.appendChild(b)})},
renderLevels(){const m=$("levelMap");m.innerHTML="";for(let i=1;i<=TF_CONTENT.levelCount;i++){const b=document.createElement("button");const unlocked=i<=S.level;b.className="level "+(unlocked?"":"locked")+" "+(i===S.level?"current":"");b.disabled=!unlocked;b.innerHTML=`<b>${unlocked?i:"🔒"}</b><small>${"★".repeat(S.stars[i]||0)}${"☆".repeat(3-(S.stars[i]||0))}</small>`;b.onclick=()=>this.start(i,S.theme);m.appendChild(b)}$("levelProgress").textContent=`${S.level} / ${TF_CONTENT.levelCount}`;},
renderThemes(){const list=$("themeList");list.innerHTML="";Object.values(TF_CONTENT.themes).forEach(t=>{const b=document.createElement("button");b.className="theme-row "+(S.theme===t.id?"selected":"");b.innerHTML=`<span class="theme-icon">${t.icon}</span><div><b>${t.name}</b><small>${t.desc}</small></div><i>${S.theme===t.id?"✓":"›"}</i>`;b.onclick=()=>{S.theme=t.id;this.save();this.renderThemes();this.renderHome();this.toast(t.name+" selected")};list.appendChild(b)})},
showAchievements(){this.modal(`<p class="eyebrow">MILESTONES</p><h2>Achievements</h2><div class="achievement-list">${TF_CONTENT.achievements.map(a=>`<div class="achievement ${S.ach.includes(a.id)?"done":""}"><span>${a.icon}</span><div><b>${a.name}</b><small>${a.desc}</small></div><i>${S.ach.includes(a.id)?"✓":"○"}</i></div>`).join("")}</div>`)},
daily(){const d=new Date().toISOString().slice(0,10);const seed=[...d].reduce((a,c)=>a+c.charCodeAt(0),0);this.modal(`<p class="eyebrow">TODAY</p><h2>Daily Challenge</h2><div class="daily-card"><span>☀️</span><b>Daily Board #${seed%999+1}</b><small>A fresh puzzle is generated from today's date.</small><button id="dailyPlay" class="primary">Play Daily →</button></div>`);$("dailyPlay").onclick=()=>{this.closeModal();this.start(Math.max(1,seed%Math.min(S.level,TF_CONTENT.levelCount)+1),S.theme)}},
modal(html){$("modalContent").innerHTML=html;$("modal").classList.add("open")},closeModal(){$("modal").classList.remove("open")}
};
document.addEventListener("DOMContentLoaded",()=>{
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
$("brandBtn").onclick=()=>UI.show("homeScreen");$("playBtn").onclick=()=>UI.start();$("dailyBtn").onclick=()=>UI.daily();$("achBtn").onclick=()=>UI.showAchievements();$("seeAllThemes").onclick=()=>UI.show("themesScreen");$("closeModal").onclick=()=>UI.closeModal();$("modal").onclick=e=>{if(e.target.id==="modal")UI.closeModal()};
$("levelsFromResult").onclick=()=>UI.show("levelsScreen");$("soundBtn").onclick=()=>{S.sound=!S.sound;UI.save();$("soundBtn").textContent=S.sound?"🔊":"🔇"};$("exitGame").onclick=()=>{game&& (game.running=false);UI.show("homeScreen");UI.renderHome()};
document.querySelectorAll(".bottom-nav button").forEach(b=>b.onclick=()=>{if(game)game.running=false;UI.show(b.dataset.nav);if(b.dataset.nav==="levelsScreen")UI.renderLevels();if(b.dataset.nav==="themesScreen")UI.renderThemes();if(b.dataset.nav==="homeScreen")UI.renderHome()});
document.querySelectorAll(".tool").forEach(b=>b.onclick=()=>{if(!game)return;const k=b.dataset.tool;k==="undo"?game.undo():k==="hint"?game.hintMove():k==="shuffle"?game.shuffle():game.wild()});
$("soundSetting").onclick=()=>{$("soundBtn").click();$("soundSetting").querySelector(".toggle").classList.toggle("on",S.sound)};$("musicSetting").onclick=()=>{$("musicSetting").querySelector(".toggle").classList.toggle("on")};
$("resetSetting").onclick=()=>{if(confirm("Reset all TileFusion progress?")){localStorage.removeItem("tf_state");location.reload()}};
const canvas=$("board");canvas.addEventListener("pointerdown",e=>{if(!game)return;const r=canvas.getBoundingClientRect();game.click(e.clientX-r.left,e.clientY-r.top)});window.addEventListener("resize",()=>game&&game.resize());
UI.renderHome();UI.renderLevels();UI.renderThemes();
});